### PR TITLE
My take on NIR+NDVI and CSWIR+NDVI presets

### PR DESCRIPTION
**Pull request by zeke800**
I wish it would be better but it works. Please tell me if you need to change anything! It occasionally over-exposes a few passes (the white clouds look too white sometimes, but mostly it's fine). Also updated the MTVZA composites since ch7 is broken now.
image
image
image
image

### CODE REVIEW

**Comment by Xerbo** [comment]
I have touched up (well more like completely rewritten) these:
```
[NIR+NDVI]
description = NIR with NDVI on land
category = Blended Composites
author = Zeke800
imagers = AVHRR|MSU-MR|VIRR
expression = ch2, max(ch2, (ch2-ch1)/(ch2+ch1)+0.05), ch1
[SWIR+NDVI]
description = SWIR with NDVI on land
category = Blended Composites
author = Zeke800
imagers = AVHRR|MSU-MR|VIRR
expression = SWIR, max(ch2, (ch2-ch1)/(ch2+ch1)+0.05), ch1
[CSWIR+NDVI]
description = CSWIR with NDVI on vegetated land
category = Blended Composites
author = Zeke800
imagers = AVHRR|MSU-MR|VIRR
expression = max(SWIR,min(ch2,ch1)), max(ch2, (ch2-ch1)/(ch2+ch1)+0.05), ch1
```

How do they look?

Meteor-M22_MSU-MR_20220226-131708_NIR+NDVI
Meteor-M22_MSU-MR_20220226-131708_SWIR+NDVI
Meteor-M22_MSU-MR_20220226-131708_CSWIR+NDVI

**Comment by zeke800** [comment]
I love them!! The only thing is that it occasionally colors clouds and does not work well in the darkness - nothing that can be fixed here I think. When I was writing the presets I was thinking more of a very slight enhancement to the image to contribute to the (kind of) natural color feel... I didn't realize they were for large shadings of green like that. Also I think the green color is a bit too harsh, but nothing that can't be fixed :)

**Comment by Xerbo** [comment]
I mean its all up to personal preference in the end, which is why its an easily editable file. But this is what came to mind when I thought "NIR+NDVI".

**Comment by Xerbo** [comment]
Any thoughts on where to go from here?

**Pull request closed without merging**
