### PR TITLE
(More) presets

### PR DESCRIPTION
**Pull request by zeke800**
Added a preset for mixing visible (or near-ir anyways) with other channels. Some fantastic colors there!
vis+ir

### CODE REVIEW

**Comment by Xerbo** [comment]
This perset is the same as [Day Microphysics RGB](http://www.eumetrain.org/rgb_quick_guides/quick_guides/DaymicroRGB.pdf). Also ch1 is visible not NIR.

**Comment by Xerbo** [comment]
You might also be intrested in [Night Microphysics](https://weather.msfc.nasa.gov/sport/training/rgb_ntmicro/RGB%20Nighttime%20Microphysics%20Reference%20Guide.pdf)

**Comment by zeke800** [comment]
So sorry... I didn't know :) ;) I just was playing around with the compositor and thought it looked really cool... thanks for giving it a chance though anyways :)

**Comment by zeke800** [comment]
I can rename it to "Daytime Microphysics" though if you want :)

**Comment by zeke800** [comment]
I created a new pull with the changes

**Pull request closed without merging**
